AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sns-latency-test

  Sample SAM Template for sns-latency-test

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3


Resources:

  PublisherFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: publisher/
      Handler: app.lambda_handler
      Runtime: python3.7
      Policies:
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt MyTopic.TopicName
      Environment:
        Variables:
          TOPIC_ARN: !Ref MyTopic
      Events:
        GetRequest:
          Type: Api
          Properties:
            Path: /invoke
            Method: post
  SubscriberFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: subscriber/
      Handler: app.lambda_handler
      Runtime: python3.7
      Events:
        SNSMessage:
          Type: SNS
          Properties:
            Topic: !Ref MyTopic
  MyTopic:
    Type: AWS::SNS::Topic

Outputs:

  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Publisher function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/invoke/"
